# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit build to internal testing track"
  lane :internal do |options|
    upload_to_play_store(
      track: 'internal',
      skip_upload_metadata: true,
      skip_upload_apk: true,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_screenshots: true,
      version_name: options[:version_name],
      version_code: options[:version_code],
      skip_upload_images: true,
      skip_upload_changelogs: true,
    )
  end

  lane :alpha do |options| 
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'alpha',
      track_promote_release_status: 'draft',
      version_name: options[:version_name],
      version_code: options[:version_code],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_aab: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_changelogs: true
    )
  end

  lane :production do |options| 
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: 'production',
      track_promote_release_status: 'draft',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_aab: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_changelogs: true
    )
    end
end
