name: Generate changelog for alpha version

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build alpha AAB 
    types:
      - completed 
   
jobs:
  alpha-changelogs:
    name: Generate alpha changelog
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6 
        with:
          fetch-depth: 0 

      - uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md

      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          draft: true
          prerelease: true
