name: Build alpha releases and upload to stores

on:
  push:
    tags:
      - "**-alpha*"

jobs:
  build_aab:
    name: Build AAB
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: "3.3.10"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: "android"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "22"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x

      - name: Generate version code
        id: version-code
        run: |
          echo -n "code=$(git rev-list --count ${{ github.ref }})" >> $GITHUB_OUTPUT

      - name: Create service account json
        run: |
          echo -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > android/zak-streamer.secret.json

      - name: Create keystore.jks
        run: |
          echo -n "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 --decode > android/keystore.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties 
          storePassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          keyAlias=upload
          storeFile=../keystore.jks
          EOF

      - name: Fetch deps
        run: flutter pub get

      - name: Check flutter environment
        run: flutter --version

      - name: Build app
        run: |
          echo "Building application with version name ${{ github.ref_name }} and version code ${{ steps.version-code.outputs.code }}"
          flutter build appbundle --build-name ${{ github.ref_name }} --build-number ${{ steps.version-code.outputs.code }}

      - name: Push to internal and alpha testing track
        run: |
          bundle exec fastlane internal version_name:"${{ github.ref_name }}" version_code:${{ steps.version-code.outputs.code }}
          bundle exec fastlane alpha version_name:"${{ github.ref_name }}" version_code:${{ steps.version-code.outputs.code }}
        working-directory: android

  build_ipa:
    name: Build iOS test release
    runs-on: macos-latest
    env:
      RUBY_VERSION: "4.0.1"
      XCODE_VERSION: "26.2"
      ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
      ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
      ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_$XCODE_VERSION.app

      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Bundle install Gemfile
        timeout-minutes: 5
        run: |
          bundle install
        working-directory: ios

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x

      - name: Generate version code
        id: version-code
        run: |
          echo -n "code=$(git rev-list --count ${{ github.ref }})" >> $GITHUB_OUTPUT

      - name: Fetch deps
        run: flutter pub get

      - name: Run pod install
        run: bundle exec pod install
        working-directory: ios

      - name: Build and push to TestFlight
        run: |
          bundle exec fastlane alpha_upload version_name:"${{ github.ref_name }}" version_code:${{ steps.version-code.outputs.code }}
        working-directory: ios

  alpha-changelogs:
    name: Generate alpha changelog
    runs-on: ubuntu-latest
    needs: [build_aab, build_ipa]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md --latest

      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          draft: true
          prerelease: true
