name: Analyze and format PRs

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - .vscode/**
      - CHANGELOG.md
      - LICENSE
      - README.md
      - cliff.toml
      - .gitignore

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x

      - name: Install deps
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-pub

      - name: Test code
        run: flutter test --no-pub --coverage
